# Generated by Django 4.1.1 on 2022-09-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.IntegerField()),
                ('stud_name', models.CharField(max_length=70)),
                ('stud_email', models.EmailField(max_length=70)),
                ('stud_pass', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
